spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: ali45


  # The SQL dialect makes Hibernate generate better SQL for the chosen database


#JPA Settings
  jpa.hibernate.ddl_auto: update






